=== gbksoft/swagger/wsagger.schema.json
{
   "$schema": "http://json-schema.org/draft-04/schema#",
   "title": "wsagger.json",
   "type": "object",
   "required": ["wsagger", "info", "server", "scenarios"],
   "properties": {
      "wsagger": {
         "type": "string",
         "description": "Wsagger internal ID"
      },
      "info": {
         "type": "object",
         "required": ["version", "title"],
         "properties": {
            "description": {
               "type": "string"
            },
            "version": {
               "type": "string"
            },
            "title":  {
               "type": "string"
            }
         }
      },
      "server": {
         "type": "object",
         "required": ["proto", "host", "port", "path"],
         "properties": {
            "proto": {
               "type": "string",
               "description": "server proto"
            },
            "host": {
               "type": "string",
               "description": "server host"
            },
            "port": {
               "type": "string",
               "description": "server port"
            },
            "path": {
               "type": "string",
               "description": "server path"
            }   
         }   
      },
      "scenarios": {
         "title": "API test scenarios array",
         "type": "array",
         "items": {
            "title": "API test scenario",
            "type": "object",
            "required": ["name", "parameters", "flow"],
            "properties": {
               "name": {
                  "type": "string"
               },
               "summary": {
                  "type": "string"
               },
               "condition": {
                  "type": "string"
               },
               "operationId": {
                  "type": "string"
               },
               "parameters": {
                  "type": "array",
                  "items": {
                     "type": "object",
                     "required": ["name", "description", "in", "dataType"],
                     "properties": {
                        "name": {
                           "type": "string"
                        },
                        "description": {
                           "type": "string"
                        },
                        "in": { 
                           "enum": ["formData", "data"] 
                        },
                        "data": {
                        },
                        "dataType": {
                        }
                     }
                  }  
               },
               "flow": {
                  "type": "array",
                  "items": {
                     "type": "object",
                     "required": ["action", "key", "data"],
                     "properties": {
                        "action": {
                           "type": "string"
                        },
                        "key": {
                           "type": "string"
                        },
                        "data": {
                        }
                     }   
                  } 
               }
            }
         }   
      }
   }
}

=== gbksoft/swagger/alexr_local.json
{
   "wsagger": "0.0.2",
   "info": {
      "description": "API for GBK chat",
      "version": "1.0.0",
      "title": "GBKSOFT chat API"
   },

   "server" : {
      "proto": "socket.io",
      "host" : "localhost",
      "port" : "28780",
      "path" : "/front_space"
   },
   
   "scenarios": [
       {
          "name": "connect to socket.io as token2",
          "summary": " ",
          "parameters": [
             {             
                "in": "formData",
                "name": "namespace",
                "description": "connect to socket.io",
                "dataType": "string"
             }
          ],
          "operationId": "connect",
          "flow": [
             {
                "action": "connect", 
                "key": "2", 
                "data": [{"token": "2"}]
             }
          ]
       },

       {
          "name": "connect to socket.io as alexr",
          "summary": " ",
          "parameters": [
          ],
          "operationId": "connect",
          "flow": [
             {
                "action": "login_and_connect", 
                "key": "alexr", 
                "data": [{"username": "alexr", "password": "alexr"}]
             }
          ]
       },


       {
          "name": "sendUserMessage to token2",
          "summary": " ",
          "parameters": [
          ],
          "operationId": "",
          "condition": "connect",
          "flow": [
             {
                "action": "request", 
                "key": "sendMessage", 
                "data": [{"messageText": "text: {{messageText}}", "type": "user", "recipientId": "token2"}]
             }
          ]
       }
    ]
}

=== gbksoft/swagger/chat.sc/_old/2016-10-26.local.json
{
   "wsagger": "0.0.2",
   "info": {
      "description": "API for GBK chat",
      "version": "1.0.0",
      "title": "GBKSOFT chat API"
   },

   "server" : {
      "proto": "socket.io",
      "host": "localhost",
      "port": "28780",
      "path": "/front_space"
   },

   "scenarios": [
       {
          "name": "connect to socket.io with tokenapi25",
          "summary": " ",
          "parameters": [
             {             
                "in": "formData",
                "name": "token",
                "description": "",
                "dataType": "string"
             }
          ],
          "operationId": "connect",
          "flow": [
             {
                "action": "connect", 
                "key": "api25", 
                "data": [{"token": "api25"}]
             }
          ]
       },

       {
          "name": "connect to socket.io as alexr",
          "summary": " ",
          "parameters": [
          ],
          "operationId": "connect",
          "flow": [
             {
                "action": "login_and_connect", 
                "key": "alexr", 
                "data": [{"username": "alexr", "password": "alexr"}]
             }
          ]
       },

       {
         "name": "create open group",
         "summary": " ",
         "parameters": [
         ],
         "operationId": "",
         "flow": [        
             {
                "action": "request", 
                "key": "createGroup", 
                "data": [{"name": "333", "type": "open", "userIds": []}]
             }
         ]
       },

       {
         "name": "create closed group",
         "summary": " ",
         "parameters": [
         ],
         "operationId": "",
         "flow": [        
             {
                "action": "request", 
                "key": "createGroup", 
                "data": [{"name": "333", "type": "closed", "userIds": []}]
             }
         ]
       },

       {
         "name": "send message to common group",
         "summary": " ",
          "parameters": [
             {
                "in": "formData",
                "name": "messageText",
                "description": "group message text",
                "dataType": "string"
             },
             {
                "in": "formData",
                "name": "groupId",
                "description": "group id",
                "dataType": "string"
             }
          ],
          "condition": "connect",
          "operationId": "",
          "flow": [
             {
                "action": "request", 
                "key": "sendMessage", 
                "data": [{"messageText": "@", "type": "group", "groupId": "1"}]
             }
          ]
       },

       {
         "name": "send message to group 2",
         "summary": " ",
          "parameters": [
             {
                "in": "formData",
                "name": "messageText",
                "description": "group message text",
                "dataType": "string"
             },
             {
                "in": "formData",
                "name": "groupId",
                "description": "group id",
                "dataType": "string"
             }
          ],
          "condition": "connect",
          "operationId": "",
          "flow": [
             {
                "action": "request", 
                "key": "changeGroup", 
                "data": ["2"]
             },
             {
                "action": "request", 
                "key": "sendMessage", 
                "data": [{"messageText": "@", "type": "group", "groupId": "2"}]
             }
          ]
       },

       {
          "name": "setReaded (all) to alexr",
          "summary": " ",
          "parameters": []
          ,
          "operationId": "",
          "flow": [
             {
                "action": "request", 
                "key": "setReaded", 
                "data": [{"senderId": "6"}]
             }
          ]
       },      



       {
         "name": "send message to user",
         "summary": " ",
          "parameters": [
             {
                "in": "formData",
                "name": "messageText",
                "description": "group message text",
                "dataType": "string"
             },
             {
                "in": "formData",
                "name": "recipientId",
                "description": "recipient id",
                "dataType": "string"
             }
          ],
          "condition": "connect",
          "operationId": "",
          "flow": [
             {
                "action": "request", 
                "key": "sendMessage", 
                "data": [{"messageText": "@", "type": "user", "recipientId": "6"}]
             }
          ]
       },

       {
         "name": "set status",
         "summary": " ",
          "parameters": [
             {
                "in": "formData",
                "name": "status",
                "description": "new user status",
                "dataType": "string"
             }
          ],
          "condition": "connect",
          "operationId": "",
          "flow": [
             {
                "action": "request", 
                "key": "setStatus", 
                "data": ["dnd"]
             }
          ]
       },

       {
         "name": "set status invisible",
         "summary": " ",
          "parameters": [
          ],
          "condition": "connect",
          "operationId": "",
          "flow": [
             {
                "action": "request", 
                "key": "setStatus", 
                "data": ["invisible"]
             }
          ]
       },

       {
         "name": "set status offline",
         "summary": " ",
          "parameters": [
          ],
          "condition": "connect",
          "operationId": "",
          "flow": [
             {
                "action": "request", 
                "key": "setStatus", 
                "data": ["offline"]
             }
          ]
       }

    ]
}

=== gbksoft/swagger/2016-10-25.json
{
   "wsagger": "0.0.2",
   "info": {
      "description": "API for GBK chat",
      "version": "1.0.0",
      "title": "GBKSOFT chat API"
   },

   "server" : {
      "proto": "socket.io",
      "host": "chat-nodejs.dev.gbksoft.net",
      "port": "28781",
      "path": "/front_space"
   },
   

   "scenarios": [
       {
          "name": "connect to socket.io with tokenapi25",
          "summary": " ",
          "parameters": [
             {             
                "in": "formData",
                "name": "token",
                "description": "",
                "dataType": "string"
             }
          ],
          "operationId": "connect",
          "flow": [
             {
                "action": "connect", 
                "key": "api25", 
                "data": [{"token": "api25"}]
             }
          ]
       },

       {
          "name": "connect to socket.io as alexr",
          "summary": " ",
          "parameters": [
          ],
          "operationId": "connect",
          "flow": [
             {
                "action": "login_and_connect", 
                "key": "alexr", 
                "data": [{"username": "alexr", "password": "alexr"}]
             }
          ]
       },


       {
         "name": "create open group (777)",
         "summary": " ",
         "parameters": [
         ],
         "operationId": "",
         "flow": [        
             {
                "action": "request", 
                "key": "createGroup", 
                "data": [{"id": "777", "type": "open"}]
             }
         ]
       },


       {
         "name": "send message to common group",
         "summary": " ",
          "parameters": [
             {
                "in": "formData",
                "name": "messageText",
                "description": "group message text",
                "dataType": "string"
             },
             {
                "in": "formData",
                "name": "groupId",
                "description": "group id",
                "dataType": "string"
             }
          ],
          "condition": "connect",
          "operationId": "",
          "flow": [
             {
                "action": "request", 
                "key": "sendMessage", 
                "data": [{"messageText": "@", "type": "group", "groupId": "1"}]
             }
          ]
       },

       {
         "name": "changeGroup (777)",
         "summary": " ",
         "parameters": [
         ],
         "operationId": "",
         "flow": [        
             {
                "action": "request", 
                "key": "changeGroup", 
                "data": ["777"]
             }
         ]
       },     

       {
         "name": "changeGroup (2)",
         "summary": " ",
         "parameters": [
         ],
         "operationId": "",
         "flow": [        
             {
                "action": "request", 
                "key": "changeGroup", 
                "data": ["2"]
             }
         ]
       },     

       {
          "name": "setReaded all from tokenapi25",
          "summary": " ",
          "parameters": [
          ],
          "operationId": "",
          "condition": "connect",
          "flow": [
             {
                "action": "request", 
                "key": "setReaded", 
                "data": [{"senderId": "tokenapi25"}]
             }
          ]
       },
 
       {
          "name": "sendUserMessage to alexr",
          "summary": " ",
          "parameters": [
          ],
          "operationId": "",
          "condition": "connect",
          "flow": [
             {
                "action": "request", 
                "key": "sendMessage", 
                "data": [{"messageText": "text to alexr: {{messageText}}", "type": "user", "recipientId": "6"}]
             }
          ]
       },

       {
          "name": "sendUserMessage to tokenapi25",
          "summary": " ",
          "parameters": [
          ],
          "operationId": "",
          "condition": "connect",
          "flow": [
             {
                "action": "request", 
                "key": "sendMessage", 
                "data": [{"messageText": "text to tokenapi25: {{messageText}}", "type": "user", "recipientId": "tokenapi25"}]
             }
          ]
       }
    ]
}

=== gbksoft/swagger/chat.sc/_old/wsagger0.json
{
   "wsagger": "0.0.2",
   "info": {
      "description": "API for GBK chat",
      "version": "1.0.0",
      "title": "GBKSOFT chat API"
   },

   "server" : {
      "proto": "socket.io",
      "host": "{{{host}}}",
      "port": "{{{port}}}",
      "path": "{{{path}}}"
   },
   
   "scenarios": [
       {
          "name": "connect to socket.io as token2",
          "summary": " ",
          "parameters": [
             {             
                "in": "formData",
                "name": "namespace",
                "description": "connect to socket.io",
                "dataType": "string"
             }
          ],
          "operationId": "connect",
          "flow": [
             {
                "action": "connect", 
                "key": "2", 
                "data": []
             }
          ]
       },

       {
          "name": "connect to socket.io as token3",
          "summary": " ",
          "parameters": [
             {             
                "in": "formData",
                "name": "namespace",
                "description": "connect to socket.io",
                "dataType": "string"
             }
          ],
          "operationId": "connect",
          "flow": [
             {
                "action": "connect", 
                "key": "3", 
                "data": []
             }
          ]
       },

       {
          "name": "getUsers: notInGroup 333",
          "summary": " ",
          "parameters": [
          ],
          "operationId": "getUsers",
          "flow": [        
             {
                "action": "request", 
                "key": "getUsers", 
                "data": [{"notInGroup": "333"}]
             }
          ]
       },


       {
          "name": "getUsers: allRegistered",
          "summary": " ",
          "parameters": [
          ],
          "operationId": "getUsers",
          "flow": [        
             {
                "action": "request", 
                "key": "getUsers", 
                "data": [{"allRegistered": "1"}]
             }
          ]
       },

       {
          "name": "setStatus: do not disturb!",
          "summary": " ",
          "parameters": [
          ],
          "operationId": "getUsers",
          "flow": [        
             {
                "action": "request", 
                "key": "setStatus", 
                "data": ["dnd"]
             }
          ]
       },


       {
          "name": "send \"userIsWriting\" to token3",
          "summary": " ",
          "parameters": [
          ],
          "operationId": "userIsWriting",
          "flow": [        
             {
                "action": "request", 
                "key": "userIsWriting", 
                "data": ["token3"]
             }
          ]
       },

       {
          "name": "sendUserMessage to token3",
          "summary": " ",
          "parameters": [
             {
                "in": "formData",
                "name": "messageText",
                "description": "user message text",
                "dataType": "string"
             },
             {
                "in": "formData",
                "name": "recipientId",
                "description": "recipient id",
                "dataType": "string"
             }
          ],
          "operationId": "",
          "condition": "connect",
          "flow": [
             {
                "action": "request", 
                "key": "sendMessage", 
                "data": [{"messageText": "text: {{messageText}}", "type": "user", "recipientId": "token3"}]
             }
          ]
       },

       {
          "name": "setReaded (all) to token2",
          "summary": " ",
          "parameters": []
          ,
          "operationId": "",
          "flow": [
             {
                "action": "request", 
                "key": "setReaded", 
                "data": [{"senderId": "token2"}]
             }
          ]
       },

       {
         "name": "create closed group",
         "summary": " ",
         "parameters": [
         ],
         "operationId": "",
         "flow": [        
             {
                "action": "request", 
                "key": "createGroup", 
                "data": [{"userIds": ["token3"]}]
             }
         ]
       },

       {
         "name": "create closed group (333)",
         "summary": " ",
         "parameters": [
         ],
         "operationId": "",
         "flow": [        
             {
                "action": "request", 
                "key": "createGroup", 
                "data": [{"id": "333", "userIds": ["token3"]}]
             }
         ]
       },
   
       {
         "name": "changeGroup (333)",
         "summary": " ",
         "parameters": [
         ],
         "operationId": "",
         "flow": [        
             {
                "action": "request", 
                "key": "changeGroup", 
                "data": ["333"]
             }
         ]
       },     

       {
         "name": "create open group",
         "summary": " ",
         "parameters": [
         ],
         "operationId": "",
         "flow": [        
             {
                "action": "request", 
                "key": "createGroup", 
                "data": [{}]
             }
         ]
       },

       {
         "name": "create open group (777)",
         "summary": " ",
         "parameters": [
         ],
         "operationId": "",
         "flow": [        
             {
                "action": "request", 
                "key": "createGroup", 
                "data": [{"id": "777"}]
             }
         ]
       },


       {
         "name": "changeGroup (777)",
         "summary": " ",
         "parameters": [
         ],
         "operationId": "",
         "flow": [        
             {
                "action": "request", 
                "key": "changeGroup", 
                "data": ["777"]
             }
         ]
       },     

       {
          "name": "sendGroupMessage",
          "summary": " ",
          "parameters": [
             {
                "in": "formData",
                "name": "messageText",
                "description": "group message text",
                "dataType": "string"
             },
             {
                "in": "formData",
                "name": "groupId",
                "description": "group id",
                "dataType": "string"
             }
          ],
          "condition": "connect",
          "operationId": "",
          "flow": [
             {
                "action": "request", 
                "key": "changeGroup", 
                "data": ["333"]
             },
             {
                "action": "response", 
                "key": "message", 
                "data": [{"messageText": "@", "groupId": "333"}]
             }
          ]
       },
   
       {
          "name": "sendBroadcastMessage",
          "summary": " ",
          "parameters": [
             { 
               "in": "formData",
               "name": "messageText",
               "description": "broadcast message text",
                "dataType": "string"
             }
          ],
          "condition": "connect",
          "operationId": "",
          "flow": [
             {
                "action": "request", 
                "key": "sendMessage", 
                "data": [{"messageText": "@", "type": "broadcast"}]
             }
          ]
       }
    ]
}
