=== gbksoft/swagger/schema/wsagger.schema.json
{
   "$schema": "http://json-schema.org/draft-04/schema#",
   "title": "wsagger.json",
   "type": "object",
   "required": ["wsagger", "info", "server_", "scenarios"],
   "properties": {
      "wsagger": {
         "type": "string",
         "description": "Wsagger version"
      },
      "info": {
         "type": "object",
         "required": ["version", "title"],
         "properties": {
            "description": {
               "type": "string"
            },
            "version": {
               "type": "string"
            },
            "title":  {
               "type": "string"
            }
         }
      },
      "server_": {
         "type": "object"
      },
      "user_": {
         "type": "object"
      },
      "scenarios": {
         "title": "API test scenarios array",
         "type": "array",
         "items": {
            "title": "API test scenario",
            "type": "object",
            "required": ["name", "parameters", "flow"],
            "properties": {
               "name": {
                  "type": "string"
               },
               "parameters": {
                  "type": "array",
                  "items": {
                     "type": "object",
                     "required": ["in", "name", "description", "dataType"],
                     "properties": {
                        "name": {
                           "type": "string"
                        },
                        "description": {
                           "type": "string"
                        },
                        "dataType": {
                           "type": "string"
                        }
                     }
                  }
               },
               "flow": {
                  "type": "array",
                  "items": {
                     "type": "object",
                     "properties": {
                        "worker": {
                           "type": "string"
                        },
                        "action": {
                           "type": "string"
                        },
                        "data": {
                        },
                        "result": {
                        },
                        "waitForResponse": {
                           "type": "object",
                           "required": ["delay"],
                           "properties": {
                              "delay": {
                                 "type": "integer"
                              },
                              "data": {
                              }
                           }
                        }
                     }
                  }
               }
            }
         }
      }
   }
}

=== gbksoft/swagger/2.sc/2_send_message_to_common.wsagger.json
{
   "wsagger": "0.0.3",
   "info": {
      "description": "GBKSOFT chat API",
      "version": "1.0.0",
      "title": "GBKSOFT chat API"
   },

   "server_" : {
      "loc":  { "proto": "socket.io", "host": "127.0.0.1",                    "port": "28780", "path": "/front_space" },
      "dev":  { "proto": "socket.io", "host": "chat-nodejs.dev.gbksoft.net",  "port": "28781", "path": "/front_space" },
      "test": { "proto": "socket.io", "host": "chat-nodejs.test.gbksoft.net", "port": "28782", "path": "/front_space" },
      "live": { "proto": "socket.io", "host": "chat-nodejs.live.gbksoft.net", "port": "28783", "path": "/front_space" }
   },

   "user_" : {
       "2":  { "token": "2" },
       "3":  { "token": "3" },
       "4":  { "token": "4" }
   },


   "scenarios": [
      {
         "name": "send and receive message in common group",
         "parameters": [
            { "in": "!!!!!!!!", "name": "messageText", "description": "", "dataType": "string" }
         ],
         "flow": [
            { "worker": "2",  "action": "connect", "data": [{"token": "4"}], 
              "waitForResponse": { "delay": 3000, "data": [["connected", {}], ["messageGroup", {"messageText" : "{{messageText}}"}]] }},

            { "action": "connect", "data": [{"token": "{{token}}"}], 
              "waitForResponse": { "delay": 3000, "data": [["connected", {}]] }},             
            { "action": "request", "data": ["sendMessage", {"type": "group", "groupId": "0", "messageText": "{{messageText}}"}], 
              "waitForResponse": { "delay": 3000, "data": [["message", {}]] }}
          ]
      }
   ]
}

=== gbksoft/swagger/_chat/_new/2_moderate_common_group.wsagger.json
{
   "wsagger": "0.0.3",
   "info": {
      "description": "GBKSOFT chat API",
      "version": "1.0.0",
      "title": "GBKSOFT chat API"
   },
   "server_" : {
      "loc":  { "proto": "socket.io", "host": "127.0.0.1",                    "port": "28780", "path": "/front_space" },
      "dev":  { "proto": "socket.io", "host": "chat-nodejs.dev.gbksoft.net",  "port": "28781", "path": "/front_space" },
      "test": { "proto": "socket.io", "host": "chat-nodejs.test.gbksoft.net", "port": "28782", "path": "/front_space" },
      "live": { "proto": "socket.io", "host": "chat-nodejs.live.gbksoft.net", "port": "28783", "path": "/front_space" }
   },

   "user_" : {
       "2":  { "token": "2" },
       "3":  { "token": "3" }
   },

   "scenarios": [
       {
          "name": "change group",
          "parameters": [
             { "in": "formData", "name": "token", "description": "", "dataType": "string" },
             { "in": "!!!!!!!!", "name": "messageText", "description": "", "dataType": "string" }
          ],
          
          "flow": [
          
            { "worker": "2",  "action": "connect", "data": [{"token": "2"}], 
              "waitForResponse": { "delay": 3000, "data": [["connected"], ["disconnect"]] }},

            { "worker": "2",  "action": "connect", "data": [{"token": "2"}], 
              "waitForResponse": { "delay": 3000, "data": [["connected"], ["restrictedRights"]] }},

            { "action": "connect", "data": [{"token": "5"}], 
              "waitForResponse": { "delay": 3000, "data": [["connected", {}]] }},

            { "action": "request", "data": ["restrictUsers", {"groupId": "0", "period": -1, "userIds": ["1000002"]}], 
              "waitForResponse": { "delay": 3000, "data": [["restrictedRights",  {"groupId": "0", "period": -1, "userIds": ["1000002"]}]] }}
          ]
       }
    ]
}

=== gbksoft/swagger/chat.sc/change_user_role.wsagger.json
{
   "wsagger": "0.0.3",
   "info": {
      "description": "GBKSOFT chat API",
      "version": "1.0.0",
      "title": "GBKSOFT chat API"
   },

   "server_" : {
      "loc":  { "proto": "socket.io", "host": "127.0.0.1",                    "port": "28780", "path": "/front_space" },
      "dev":  { "proto": "socket.io", "host": "chat-nodejs.dev.gbksoft.net",  "port": "28781", "path": "/front_space" },
      "test": { "proto": "socket.io", "host": "chat-nodejs.test.gbksoft.net", "port": "28782", "path": "/front_space" },
      "live": { "proto": "socket.io", "host": "chat-nodejs.live.gbksoft.net", "port": "28783", "path": "/front_space" }
   },

   "user_" : {
       "2":  { "token": "2" },
       "3":  { "token": "3" }
   },

   "scenarios": [
       {
          "name": "change user role",
          "parameters": [
             { "in": "formData", "name": "token",   "description": "", "dataType": "string" },
             { "in": "formData", "name": "userId",  "description": "", "dataType": "string", "default_in": "3"}
          ],
          "flow": [
             { "action": "connect", "data": [{"token": "{{token}}"}],
               "waitForResponse": { "delay": 3000, "data": [["connected", {}]] }},

             { "action": "request", "data": ["createGroup", {"type": "closed"}], 
               "waitForResponse": { "delay": 3000, "data": [["newGroup",  {"id": "{{!groupId}}"}]] }},

             { "action": "request", "data": ["changeGroup", "{{groupId}}"], 
               "waitForResponse": { "delay": 3000, "data": [
                  ["joinedTo",  {"groupId": "{{groupId}}"}],
                  ["history"]
               ]}
             },


             { "action": "request", "data": ["changeUsersRoles", {"groupId": "{{groupId}}", "role": "moderator", "userIds": ["{{userId}}"]}], 
               "waitForResponse": { "delay": 3000, "data": [["newRole",  {"groupId": "{{groupId}}", "role": "moderator", "userIds": ["{{userId}}"]}]] }}
          ]
       }
    ]
}

=== gbksoft/swagger/_chat/send_and_receive_message_in_common.json
{
   "wsagger": "0.0.3",
   "info": {
      "description": "GBKSOFT chat API",
      "version": "1.0.0",
      "title": "GBKSOFT chat API"
   },

   "server_" : {
      "localhost":                   { "proto": "socket.io", "host": "127.0.0.1",                   "port": "28780", "path": "/front_space" },
      "chat-nodejs.dev.gbksoft.net": { "proto": "socket.io", "host": "chat-nodejs.dev.gbksoft.net", "port": "28781", "path": "/front_space" }
   },

   "user_" : {
       "token2":     { "token": "2"                                   },
       "tokenapi25": { "token": "api25"                               },
       "pavlo":      { "username": "pavlo",    "password": "pavlo"    },
       "alexr":      { "username": "alexr",    "password": "alexr"    },
       "roman":      { "username": "roman",    "password": "roman"    },
       "olexandr":   { "username": "olexandr", "password": "olexandr" }
   },

   "scenarios": [
       {
          "name": "send and receive message in common group",
          "parameters": [
             { "in": "slave",    "name": "tokenSlave",  "description": "", "dataType": "string" },
             { "in": "!!!!!!!!", "name": "messageText", "description": "", "dataType": "string" }
          ],
          "operationId": "connect",
          "flow": [
             { "worker": "slave",  "action": "connect", "data": [{"token": "{{tokenSlave}}"}], 
               "waitForResponse": { "delay": 3000, "data": [["connected", {}]] }},
             { "worker": "slave",  
               "waitForResponse": { "delay": 3000, "data": [["message", {"messageText" : "{{messageText}}"}]] }},

             { "action": "connect", "data": [{"token": "{{token}}"}], 
               "waitForResponse": { "delay": 3000, "data": [["connected", {}]] }},             

             { "action": "request", "data": ["sendMessage", {"type": "group", "groupId": "1", "messageText": "{{messageText}}"}], 
               "waitForResponse": { "delay": 3000, "data": [["message", {}]] }}
          ]
       }
    ]
}

=== gbksoft/swagger/game.sc/connect_trial.wsagger.json
{
   "wsagger": "0.0.3",
   "info": {
      "description": "GBKSOFT chat API",
      "version": "1.0.0",
      "title": "GBKSOFT chat API"
   },

   "server_" : {
      "dev":  { "proto": "socket.io", "host": "gambling-game-node.dev.gbksoft.net", "port": "28790", "path": "/front_space" },
      "loc":  { "proto": "socket.io", "host": "127.0.0.1",                          "port": "28780", "path": "/front_space" }
   },

   "user_" : {
       "2":  { "token": "2" },
       "3":  { "token": "3" }
   },

   "scenarios": [
       {
          "name": "connect to socket.io without token",
          "summary": " ",
          "parameters": [
          ],
          "flow": [
             { "action": "connect", "data": [{ "token": ""}],
               "waitForResponse": { "delay": 3000, "data": [["CID", {}]] }
             }
          ]
       }
    ]
}

=== gbksoft/swagger/test_trial.wsagger.json
{
  "wsagger": "0.0.3",
  "info": {
      "description": "GBKSOFT chat API",
      "version": "1.0.0",
      "title": "GBKSOFT chat API"
  },

  "server_" : {
      "dev":  { "proto": "socket.io", "host": "gambling-game-node.dev.gbksoft.net", "port": "28790", "path": "/front_space" },
      "loc":  { "proto": "socket.io", "host": "127.0.0.1",                          "port": "28780", "path": "/front_space" }
  },

  "scenarios": [
    {
      "name": "connect to socket.io without token",
      "parameters": [
      ],
          
      "flow": [
        { 
          "action": "socket_io.connect", 
            
          "wait": {"delay": 3000}, 

          "expected": [[ "CID", {}]],

          "data": { 

            "url": "http://{{server.host}}:{{server.port}}{{server.path}}",
            
            "query": {}

          }         
        }  
      ]
    }
  ]  
}

=== gbksoft/swagger/game.sc/get_users_online.wsagger.json
{
   "wsagger": "0.0.3",
   "info": {
      "description": "GBKSOFT chat API",
      "version": "1.0.0",
      "title": "GBKSOFT chat API"
   },

   "server_" : {
      "dev": { "proto": "socket.io", "host": "gambling-game-node.dev.gbksoft.net", "port": "28790", "path": "/front_space" },
      "loc": { "proto": "socket.io", "host": "127.0.0.1",                          "port": "28780", "path": "/front_space" }
   },

   "user_" : {
       "4loc":  { "token": "T4_h92ldg6w5GiwAAAA1d420d6fec64fdbd6e707413570850341f64c1d8a0f4f45a279c32ce69fcc3ec64_3YLAfq6S14xjAR4I3dzbaFSHmfvtVp_XR_RJMt83DkPKQ2mQvYGFld2_grqtb5" }




   },

   "scenarios": [
       {
          "name": "connect to socket.io with token",
          "summary": " ",
          "parameters": [
             { "in": "formData", "name": "token", "description": "", "dataType": "string" }
          ],
          "flow": [
             { "action": "connect", "data": [{"token": "{{token}}"}],
               "wait": { "delay": 3000, "expected": [["connectedTo", {"APIVersion": "Gambling.1.0.0"}]] }
             },
             
             { 
               "action": "request", "data": ["getUsersOnline", {"type": "facebook"}], 
               "wait": { "delay": 3000, "expected": [["usersOnline",  {"type": "facebook", "userIds": []}]] }
             }
                          
             
          ]
       }
    ]
}

=== gbksoft/swagger/game.sc/connect_with_token.wsagger.json
{
   "wsagger": "0.0.3",
   "info": {
      "description": "GBKSOFT chat API",
      "version": "1.0.0",
      "title": "GBKSOFT chat API"
   },

   "server_" : {
      "loc": { "proto": "socket.io", "host": "127.0.0.1",                          "port": "28780", "path": "/front_space" },
      "dev": { "proto": "socket.io", "host": "gambling-game-node.dev.gbksoft.net", "port": "28790", "path": "/front_space" }
   },

   "user_" : {
       "2":  { "token": "2" },
       "3":  { "token": "3" }
   },

   "scenarios": [
       {
          "name": "connect to socket.io with token",
          "summary": " ",
          "parameters": [
             { "in": "formData", "name": "token", "description": "", "dataType": "string", "default_in": "/front_space#Hgzj1AMHqR5qgB6fAAAD|48fcb6be303bfe74c98a3116f158826aa4ec8936c5013c7b05a8ec5f8f55b0735_BS-x101q7VaFzLq95EijBqcWHRTdJfTdz0pM_GK5dC3OoHnSYsDDw2tVA9fiKe" }
          ],
          "flow": [
             { "action": "connect", "data": [{"token": "{{token}}"}],
               "waitForResponse": {
                  "delay": 3000, 
                  "data": [
                     ["connectedTo", {"APIVersion": "Gambling.1.0.0"}]
                  ]
               }
             }
          ]
       }
    ]
}
