=== gbksoft/swagger/schema/wsagger.schema.json
{
   "$schema": "http://json-schema.org/draft-04/schema#",
   "title": "wsagger.json",
   "type": "object",
   "required": ["wsagger", "info", "server_", "scenarios"],
   "properties": {
      "wsagger": {
         "type": "string",
         "description": "Wsagger version"
      },
      "info": {
         "type": "object",
         "required": ["version", "title"],
         "properties": {
            "description": {
               "type": "string"
            },
            "version": {
               "type": "string"
            },
            "title":  {
               "type": "string"
            }
         }
      },
      "server_": {
         "type": "object"
      },
      "user_": {
         "type": "object"
      },
      "scenarios": {
         "title": "API test scenarios array",
         "type": "array",
         "items": {
            "title": "API test scenario",
            "type": "object",
            "required": ["name", "parameters", "flow"],
            "properties": {
               "name": {
                  "type": "string"
               },
               "parameters": {
                  "type": "array",
                  "items": {
                     "type": "object",
                     "required": ["in", "name", "description", "dataType"],
                     "properties": {
                        "name": {
                           "type": "string"
                        },
                        "description": {
                           "type": "string"
                        },
                        "dataType": {
                           "type": "string"
                        }
                     }
                  }
               },
               "flow": {
                  "type": "array",
                  "items": {
                     "type": "object",
                     "properties": {
                        "worker": {
                           "type": "string"
                        },
                        "action": {
                           "type": "string"
                        },
                        "data": {
                        },
                        "result": {
                        },
                        "waitForResponse": {
                           "type": "object",
                           "required": ["delay"],
                           "properties": {
                              "delay": {
                                 "type": "integer"
                              },
                              "data": {
                              }
                           }
                        }
                     }
                  }
               }
            }
         }
      }
   }
}

=== gbksoft/swagger/_chat/send_message_to_common.json
{
   "wsagger": "0.0.3",
   "info": {
      "description": "GBKSOFT chat API",
      "version": "1.0.0",
      "title": "GBKSOFT chat API"
   },

   "server_" : {
      "localhost":                   { "proto": "socket.io", "host": "127.0.0.1",                   "port": "28780", "path": "/front_space" },
      "chat-nodejs.dev.gbksoft.net": { "proto": "socket.io", "host": "chat-nodejs.dev.gbksoft.net", "port": "28781", "path": "/front_space" }
   },

   "user_" : {
       "token2":     { "token": "2"                                   },
       "tokenapi25": { "token": "api25"                               },
       "pavlo":      { "username": "pavlo",    "password": "pavlo"    },
       "alexr":      { "username": "alexr",    "password": "alexr"    },
       "roman":      { "username": "roman",    "password": "roman"    },
       "olexandr":   { "username": "olexandr", "password": "olexandr" }
   },

   "scenarios": [
       {
          "name": "send message to common group",
          "parameters": [
             { "in": "formData", "name": "token",       "description": "", "dataType": "string" },
             { "in": "!!!!!!!!", "name": "messageText", "description": "", "dataType": "string" }
          ],
          "flow": [
             { "action": "connect", "data": [{"token": "{{token}}"}],
               "waitForResponse": { "delay": 3000, "data": [["connected", {}]] }},
             { 
               "waitForResponse": { "delay": 3000, "data": [                 ] }},
             { "action": "request", "data": ["sendMessage", {"type": "group", "groupId": "1", "messageText": "{{messageText}}"}], 
               "waitForResponse": { "delay": 3000, "data": [["message",   {}]] }}
          ]
       }
    ]
}
